ignore Xilinx return code LD_LIB bug

diff --git a/scripts/buildhdl/build_fpgaTop b/scripts/buildhdl/build_fpgaTop
--- a/scripts/buildhdl/build_fpgaTop
+++ b/scripts/buildhdl/build_fpgaTop
@@ -127,26 +127,26 @@ endif
 
 ngdbuild -sd ../../coregen/$PCIe -sd ../../coregen/$FFT  -sd ../../coregen/$DDC \
   -aul -aut -uc $buildTarget.ucf -p $PART fpgaTop_csi.ngc fpgaTop.ngd  
-if ($status != 0) then
-  echo NGDBuild returned non-zero status
-  exit 1
-endif
+#if ($status != 0) then
+#  echo NGDBuild returned non-zero status
+#  exit 1
+#endif
 
 #map -p $PART -w -logic_opt on -ol high -xe n -mt on -t 1 \
 map -p $PART -w -logic_opt on -xe n -mt on -t 1 \
   -register_duplication on -ir off \
   -pr off -lc off -power off -o fpgaTop_map.ncd fpgaTop.ngd fpgaTop.pcf 
-if ($status != 0) then
-  echo MAP returned non-zero status
-  exit 1
-endif
+#if ($status != 0) then
+#  echo MAP returned non-zero status
+#  exit 1
+#endif
 
 #par -w -ol high -xe n -t 1 fpgaTop_map.ncd fpgaTop.ncd fpgaTop.pcf 
 par -w -xe n fpgaTop_map.ncd fpgaTop.ncd fpgaTop.pcf 
-if ($status != 0) then
-  echo PAR returned non-zero status
-  exit 1
-endif
+#if ($status != 0) then
+#  echo PAR returned non-zero status
+#  exit 1
+#endif
 
 trce -v 20 -fastpaths -xml fpgaTop.twx fpgaTop.ncd -o fpgaTop.twr fpgaTop.pcf 
 
